version: "3.9"

services:
  web:
    build: .
    container_name: shop_web
    working_dir: /app/
    environment:
      # Django
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure-dev-key}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-true}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-*}
      # DB
      DATABASE_URL: ${DATABASE_URL}
      DB_SSL_REQUIRE: ${DB_SSL_REQUIRE:-1}
    volumes:
      - ./virtuallabshop:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000"


  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: sh -c " trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet || true; sleep 12h & wait $${!}; done"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./virtuallabshop:/app
      - /app/node_modules
      - static_volume:/static
      - media_volume:/media
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  static_volume:
  media_volume:
  certbot-web:
  letsencrypt:
